version: "3"
services:
  dataserver:
    # This image does not exist on docker hub, nor any other registry...
    # must be built locally using the build script.
    image: nti-dataserver:latest
    container_name: dataserver
    depends_on:
      - "memcached"
      - "redis"
    networks:
      - app-network
    expose:
      - 8081
    volumes:
      - ./content/:/srv/content
      - ./var/assets/:/srv/assets
      - ./var/data/:/code/data
      - ./var:/code/var

  memcached:
    image: memcached:alpine
    # container_name: memcached
    networks:
      - app-network
    expose:
      - 11211

  redis:
    image: redis:alpine
    # container_name: redis
    networks:
      - app-network
    sysctls:
      net.core.somaxconn: 1024

  nginx:
    image: nginx:alpine
    # container_name: nginx
    depends_on:
      - dataserver
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network
    volumes:
      - ./content:/srv/content/
      - ./var/assets/:/srv/assets/
      - ./node_modules/:/srv/node_modules
      - ./node_modules/@nti/client-sites-default/dist/:/srv/default-assets/site-assets

      - ./configs/nginx/status.html:/var/www/public/index.html
      - ./configs/nginx/conf.d/:/etc/nginx/conf.d/
      - ./configs/nginx/certs/:/var/run/nti-dev/

networks:
  app-network:
    driver: bridge
