version: "3"
services:
  dataserver:
    # This image does not exist on docker hub, nor any other registry...
    # must be built locally using the build script.
    image: nti-dataserver:latest
    container_name: nti.dataserver
    depends_on:
      - "memcached"
      - "redis"
    networks:
      - app-network
    expose:
      - 8081
    volumes:
      - ./content/:/srv/content:rw,z
      - ./var/assets/:/srv/assets:rw,z
      - ./var/data/:/code/data:rw,z
      - ./var:/code/var:rw,z

  memcached:
    image: memcached:alpine
    container_name: nti.memcached
    networks:
      - app-network
    expose:
      - 11211

  redis:
    image: redis:alpine
    container_name: nti.redis
    networks:
      - app-network
    sysctls:
      net.core.somaxconn: 1024

  nginx:
    image: nginx:alpine
    container_name: nti.nginx
    depends_on:
      - dataserver
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network
    volumes:
      - ./content:/srv/content/:ro,z
      - ./var/assets/:/srv/assets/:ro,z
      - ./node_modules/:/srv/node_modules:ro,z
      - ./node_modules/@nti/client-sites-default/dist/:/srv/default-assets/site-assets:ro,z

      - ./configs/nginx/status.html:/var/www/public/index.html:ro,z
      - ./configs/nginx/conf.d/:/etc/nginx/conf.d/:ro,z
      - ./configs/nginx/certs/:/var/run/nti-dev/:ro,z

networks:
  app-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
