version: '3'
services:
  dataserver:
    # This image does not exist on docker hub, nor any other registry... 
    # must be built locally using the build script.
    image: nti-dataserver:latest
    container_name: dataserver
    depends_on: 
      - "memcached"
      - "redis"
    networks: 
      - app-network
    expose:
      - 8081
    volumes:
      - ./content/:/srv/content
      - ./var/site-assets/:/srv/site-assets
      - ./var/data/:/code/data
      - ./var/caches:/code/var/caches
      - ./var/log:/code/var/log
      - ./var/maildir:/code/var/maildir

  memcached:
    image: memcached:alpine
    container_name: memcached
    networks: 
      - app-network
    expose:
      - 11211
  
  redis:
    image: redis:alpine
    container_name: redis
    networks:
      - app-network
    sysctls:
      net.core.somaxconn: 1024
  
  nginx:
    image: nginx:alpine
    container_name: nginx
    depends_on:
      - dataserver
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network
    volumes:
      - ./content:/var/www/public/content/
      - ./var/nginx-logs:/var/log/nginx
      - ./var/site-assets/:/var/www/public/site-assets/
      - ./configs/nginx/conf.d/:/etc/nginx/conf.d/
      - ./configs/nginx/certs/localhost.crt:/etc/ssl/certs/localhost.crt
      - ./configs/nginx/certs/localhost.key:/etc/ssl/private/localhost.key
      - ./configs/nginx/status.html:/var/www/public/index.html
      #- ./configs/nginx/favicon.ico:/var/www/public/favicon.ico

networks:
  app-network:
    driver: bridge
