version: '3'
services:
  dataserver:
    # This image does not exist on docker hub, nor any other registry... 
    # must be built locally using the build script.
    image: nti-dataserver:latest
    depends_on: 
      - "memcached"
      - "redis"
      - "nginx"
    networks: 
      - app-network
    ports:
      - "8082:8082"
    volumes:
      - ./Library/:/srv/content
      - ./data/:/code/data
      - ./var/:/code/var

  memcached:
    image: memcached
    container_name: memcached
    networks: 
      - app-network
    expose:
      - 11211
  
  redis:
    image: redis
    container_name: cache
    networks:
      - app-network
    expose:
      - 6379
    sysctls:
      net.core.somaxconn: 1024
  
  nginx:
    image: nginx
    ports:
      - "80:80"
    networks:
      - app-network
    volumes:
      - ./:/var/www
      # - ./nginx/conf.d/:/etc/nginx/conf.d/

networks:
  app-network:
    driver: bridge

volumes:
  data:
    driver: local