version: '3'
services:
  dataserver:
    # This image does not exist on docker hub, nor any other registry... 
    # must be built locally using the build script.
    image: nti-dataserver:latest
    container_name: dataserver
    depends_on: 
      - "memcached"
      - "redis"
      - "statsd"
    networks: 
      - app-network
    expose:
      - 8081
    volumes:
      - ./Library/:/srv/Library
      - ./SiteAssets/:/srv/SiteAssets
      - ./data/:/code/data
      - ./var/:/code/var

  memcached:
    image: memcached
    container_name: memcached
    networks: 
      - app-network
    expose:
      - 11211
  
  redis:
    image: redis
    container_name: cache
    networks:
      - app-network
    expose:
      - 6379
    sysctls:
      net.core.somaxconn: 1024
  
  nginx:
    image: nginx
    container_name: nginx
    depends_on:
      - dataserver
    ports:
      - "80:80"
    networks:
      - app-network
    volumes:
      - ./var/log/nginx:/var/log/nginx
      - ./Library:/var/www/public/content/
      - ./SiteAssets/:/var/www/public/site-assets/
      - ./configs/nginx/conf.d/:/etc/nginx/conf.d/

  statsd:
    image: statsd/statsd
    container_name: statsd
    networks: 
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  data:
    driver: local