version: "3.2"
services:
  dataserver:
    # This image does not exist on docker hub, nor any other registry...
    # must be built locally using the build script.
    image: nti-dataserver:latest
    container_name: nti.dataserver
    depends_on:
      - "memcached"
      - "redis"
      - "solr"
    networks:
      - app-network
    expose:
      - 8081
    volumes:
      - ./content/:/srv/content:rw,z,delegated
      - ./var/assets/:/srv/assets:rw,z,delegated
      - ./var/data/:/code/data:rw,z,delegated
      - ./var:/code/var:rw,z,delegated

  memcached:
    image: memcached:alpine
    container_name: nti.memcached
    networks:
      - app-network
    expose:
      - 11211

  redis:
    image: redis:alpine
    container_name: nti.redis
    networks:
      - app-network
    sysctls:
      net.core.somaxconn: 1024

  nginx:
    image: nginx:alpine
    container_name: nti.nginx
    depends_on:
      - dataserver
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network
    volumes:
      - ./content:/srv/content/:ro,z,cached
      - ./var/assets/:/srv/assets/:ro,z,cached
      - ./node_modules/:/srv/node_modules:ro,z,cached
      - ./node_modules/@nti/client-sites-default/dist/:/srv/default-assets/site-assets:ro,z,cached

      - ./configs/nginx/50x.html:/var/www/public/50x.html:ro,z,cached
      - ./configs/nginx/status.html:/var/www/public/index.html:ro,z,cached
      - ./configs/nginx/conf.d/:/etc/nginx/conf.d/:ro,z,cached
      - ./configs/nginx/certs/:/var/run/nti-dev/:ro,z,cached
      - ./configs/nginx/00-run-as-root.sh:/docker-entrypoint.d/00-run-as-root.sh:ro,z,cached

  solr:
    image: solr:7
    container_name: nti.solr
    networks:
      - app-network
    ports:
      - "8983:8983"
    volumes:
      - ./var/solr:/opt/solr/server/solr/mycores:rw,z,delegated

networks:
  app-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
