#!/bin/bash
mv /usr/bin/svn /usr/bin/_svn

if [ "$#" -ne 2 ]; then
    echo "Illegal number of parameters"
    exit 1
fi

cat > /usr/bin/svn <<EOF
#!/bin/bash
_svn "\$@" --username="$1" --password="$2"
EOF

chmod +x /usr/bin/svn
